name: Testes de Segurança com Snyk

on:
  push:
    branches:
      - main

jobs:
  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Run Snyk para verificar vulnerabilidades
      uses: snyk/actions/python@main
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
